
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BazanAI.Agronomy.Application/BazanAI.Agronomy.Application.csproj" />
    <ProjectReference Include="../../../SharedKernel/BazanAI.Infrastructure.Common/BazanAI.Infrastructure.Common.csproj" />
    <PackageReference Include="Polly" Version="8.2.0" />
  </ItemGroup>
</Project>
